services:
  - type: web
    name: msg-app
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rake assets:precompile db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: msg-app-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: msg-app-redis
          type: redis

databases:
  - name: msg-app-db

services:
  - name: msg-app-redis
    type: redis
    plan: free
